"""Flow API Client for VideoFX (Veo)"""
import asyncio
import json
import contextvars
import time
import uuid
import random
import base64
import ssl
from typing import Dict, Any, Optional, List, Union, Callable, Awaitable
from urllib.parse import quote
import urllib.error
import urllib.request
from curl_cffi.requests import AsyncSession
from src.core.logger import debug_logger
from src.core.config import config, get_yescaptcha_min_score

try:
    import httpx
except ImportError:
    httpx = None


from .mixins.base import FlowClientBaseMixin
from .mixins.auth import FlowClientAuthMixin
from .mixins.project import FlowClientProjectMixin
from .mixins.image import FlowClientImageMixin
from .mixins.video import FlowClientVideoMixin

class FlowClient(
    FlowClientBaseMixin,
    FlowClientAuthMixin,
    FlowClientProjectMixin,
    FlowClientImageMixin,
    FlowClientVideoMixin
):
    """VideoFX API客户端"""

    def __init__(self, proxy_manager, db=None):
        self.proxy_manager = proxy_manager
        self.db = db  # Database instance for captcha config
        self.labs_base_url = config.flow_labs_base_url  # https://labs.google/fx/api
        self.api_base_url = config.flow_api_base_url    # https://aisandbox-pa.googleapis.com/v1
        self.timeout = config.flow_timeout
        # 缓存每个账号的 User-Agent
        self._user_agent_cache = {}
        # 当前请求链路绑定的浏览器指纹（基于 contextvar，避免并发串扰）
        self._request_fingerprint_ctx: contextvars.ContextVar[Optional[Dict[str, Any]]] = contextvars.ContextVar(
            "flow_request_fingerprint",
            default=None
        )
        self._remote_browser_prefill_last_sent: Dict[str, float] = {}

        # Default "real browser" headers (macOS Chrome Desktop) to reduce upstream 4xx/5xx instability.
        # These will be applied as defaults (won't override caller-provided headers).
        # NOTE: Must match the UA platform (macOS) generated by _generate_user_agent.
        self._default_client_headers = {
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "\"macOS\"",
            "sec-fetch-dest": "empty",
            "sec-fetch-mode": "cors",
            "sec-fetch-site": "cross-site",
            "x-browser-channel": "stable",
            "x-browser-copyright": "Copyright 2026 Google LLC. All Rights reserved.",
            "x-browser-year": "2026",
        }

